services:
  global-mysql:
    container_name: global-mysql
    image: mysql:8.4.2
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
      - MYSQL_DATABASE=localenv
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=superdupersecret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - localenv_network
    healthcheck:
      test: mysql -umysql -psuperdupersecret localenv -e "SELECT 1;"
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  global-postgres:
    container_name: global-postgres
    image: postgres:16.3-bookworm
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=localenv
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localenv_network
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data:
  postgres_data:

networks:
  localenv_network:
    external: true
