services:
  global-mysql:
    container_name: global-mysql
    image: mysql:5.7.21
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    networks:
      - localenv_network
  global-postgres:
    container_name: global-postgres
    image: postgres:9.6.7-alpine
    platform: linux/x86_64
    networks:
      - localenv_network

networks:
  localenv_network:
    external: true
